### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [Grupo-4-Rolling-Code-45i/Backend#23]
Buenas! como va? encontre algunos comentarios en el codigo,
![image](https://github.com/Grupo-4-Rolling-Code-45i/Backend/assets/53904695/38be2490-65c9-4646-8132-9c3595a8f076)
Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by nicoquinteros23** [comment]
Perfecto Nico, trabajamos las correcciones y te avisamos, saludos!
